package com.maurooyhanart.surveyq.backend;

public class JwtTestUtils {
    public static String mockJwtToken = "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyMDJAZ21haWwuY29yIiwiaWF0IjoxNzQxNDU2Njk2LCJleHAiOjE3NDE1NDMwOTYsInJvbGVzIjpbIlVTRVIiXX0.JoYoX79xuho8j-k_NCcA6nSZEfGj0WkCGVPfg9hvmbsBIY15Yoy0iSqd--R1tRNE3SP5OM9LlZbptFcOnwPXyA";
}
